# Generated by Django 4.1.7 on 2023-03-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_funcionarios_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionarios',
            name='data_admissao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
